abstract: Perl interface to SQL Databases
author: Mark Lawrence <nomad@null.net>
build_requires: 
  DBD::SQLite: 0
  File::Temp: 0
  Test::Exception: 0
  Test::Memory::Cycle: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: GPL
name: SQL-DB
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  DBI: 0
  Scalar::Util: 0
  perl: 5.6.0
version: 0.11
