---
abstract: 'SQL database interface for Perl'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  DBD::SQLite: 1.35
  ExtUtils::MakeMaker: 6.36
  File::Temp: 0
  FindBin: 0
  Test::Database: 1.11
  Test::Differences: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-DB
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  DBI: 0
  DBIx::Connector: 0
  Data::Dumper: 0
  File::Basename: 0
  File::ShareDir: 0
  File::Slurp: 0
  File::Spec: 0
  Getopt::Long::Descriptive: 0
  Log::Any: 0
  Module::Load: 0
  Moo: 0.009011
  Sub::Exporter: 0.04
  Sub::Install: 0.04
  Template::Tiny: 0
  Term::Prompt: 0
  YAML: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: http://github.com/mlawren/sql-db.git/
version: 0.19_14
