---
abstract: 'Perl/SQL database interface'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  DBD::SQLite: 1.26
  ExtUtils::MakeMaker: 6.42
  File::Temp: 0
  Test::Database: 0
  Test::Differences: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-DB
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DBIx::Connector: 0
  Moo: 0
  Sub::Exporter: 0.04
  Sub::Install: 0.04
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: http://github.com/mlawren/sql-db.git/
version: 0.19_7
